# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0016_outflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('purchaseDate', models.DateField()),
                ('orginalCost', models.PositiveIntegerField()),
                ('depreciationRate', models.FloatField()),
                ('depreciationValue', models.PositiveIntegerField()),
                ('presentVal', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
