# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0017_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rawmaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('purchaseOrderNumber', models.PositiveIntegerField()),
                ('PurchaseOrderDate', models.DateField()),
                ('quality', models.CharField(max_length=500)),
                ('supplier', models.CharField(max_length=500)),
                ('received', models.PositiveIntegerField()),
                ('landedCostPerUnit', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
